name: EssentialsRGX
main: com.goyanov.essentials.main.EssentialsRGX
version: 1.3.1
api-version: 1.13
softdepend:
  - PlaceholderAPI
commands:
  rtp:
    description: "Телепортация в случайную точку мира"
    permission: EssentialsRGX.command.rtp
    permission-message: "Ты не можешь этого сделать!"
    aliases:
      - tpr
      - tprandom
  tpa:
    description: "Запрос на телепортацию к игроку"
    permission: EssentialsRGX.command.tpa
    permission-message: "Ты не можешь этого сделать!"
  tpaccept:
    description: "Принятие запроса на телепортацию от игрока"
    permission: EssentialsRGX.command.tpaccept
    permission-message: "Ты не можешь этого сделать!"
